### ISSUE TITLE
[FE] Remaining features

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-odoo-timesheets#45] opened 2023-07-24 09:24 UTC
- [ ] Sorting timesheets most recenty, oldest etc
- [ ] Favorite project interaction, currently it is read only
- [ ] Editing/delete local task, project, timesheet interaction
- [ ] Github login and UX for github related syncing etc
- [ ] Update package name to com.apexive.timesheet
- [x] https://github.com/djangoflow/flutter-odoo-timesheets/issues/38

cc @ivan1px

**Comment by ivan1px** [comment] 2023-08-07 15:35
Duplicate of #47

**Closed by ivan1px** 2023-08-07 15:35 UTC
