### ISSUE TITLE
Edge cases

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-odoo-timesheets#38] opened 2023-07-14 11:54 UTC
**Verify Cases:**
- [ ] When syncing an already sycned **timesheet** from odoo, the odoo task can be deleted, in this case we need to show user a pop up to choose if they want to delete the local timesheet entry as well, or want to keep it

- [ ] If an online Task or Project was deleted then the user will need to sync Task from odoo to select a Odoo project and Odoo Task. This will also update the onlineIds for local Task and Project

- [ ] If a timesheets online project id and task id was change from odoo then we will need to create a new Task or Project or both on local db and update the onlineIds there and update the local timesheet to refer to the new projectId and TaskId. Basically transfer the timesheet to the new Task.

**Questions**
- [ ] We should make a decision for when user logs out then how it should affect the local database(idea is to keep information of last time synced external id glue them together when user logs in again)

- [ ] We should store description of each timesheets separately

- [ ] We should make it very easy to modify the description of a running task. Because for the same Task(Sr Frontend Engineer) and same project(Odoo Timesheets) we can have multiple timesheets with different descriptions.

**Comment by ivan1px** [comment] 2023-08-07 15:35
Duplicate of #47

**Closed by ivan1px** 2023-08-07 15:35 UTC
